name: Testing

on:
  push:

jobs:
  node:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - uses: oven-sh/setup-bun@v1
      - run: make dep
      - run: make test
